### ISSUE TITLE
Note 기능에서 memo

### ISSUE THREAD

**Issue by briggirl2** [JJeongs/SoftwareEngineering#6]
지금 Note.v1 branch에서는 memo의 내용을 입력받을 때 한줄에 입력한것만 저장되는데

이것을 사용자가 입력을 끝낼때까지 입력을 받게해서 
여러줄로 입력한것도 memo에 저장되게 바꿀까요?

**Comment by uneap** [comment]
네 좋습니다~~~

**Comment by briggirl2** [comment]
Note.v2에 memo 수정해서 올렸습니다.
